name: instagram_clone
description: 'Instagram Clone Mobile App'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.9
  internet_connection_checker: ^1.0.0+1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0
  moment_dart: ^1.1.0
  dio: ^5.4.0
  flutter_redux: ^0.10.0
  go_router: ^13.2.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  redux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
